version: '3.8'
services:
  frontend:
    build: ./frontend
    image: system-monitoring-frontend:latest
    ports:
      - "80:80"
    networks:
      - monitoring-net
    depends_on:
      - backend
  backend:
    build: ./backend
    image: system-monitoring-backend:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
networks:
  monitoring-net:
    external: true