version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"   # expose backend on host:3000
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8081:80"     # expose frontend on host:8081
    restart: always
