version: '3.8'
services:
  frontend:
    build: ./frontend
    image: system-monitoring-frontend:latest
    ports:
      - "3001:80"  # Changed from 80:80 to 3001:80
    networks:
      - monitoring-net
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    image: system-monitoring-backend:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    restart: unless-stopped

    #--------------- 
    pid: "host"
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    environment:
      - PROCFS_PATH=/host/proc

networks:
  monitoring-net:
    external: true