version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend-container
    expose:
      - "3000"

  frontend:
    build: ./frontend
    container_name: frontend-container
    expose:
      - "80"
    depends_on:
      - backend
