version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    environment:
      - VITE_API_BASE=/api
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - /:/host:ro  # Read-only access to host system for systeminformation
    privileged: true
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge